
services:
  database:
    image: postgres:15
    container_name: postgres-tasker-app
    volumes:
      - postgres15-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    env_file:
      - docker/docker-compose-env/database.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  websocket-server:
    build:
      context: .
      dockerfile: ./docker/php-cli/Dockerfile
    image: tasker-websocket-app:v1.0
    container_name: websocket-tasker
    # restart: on-failure
    ports:
      - "8182:8182"
    command: ["php", "/app/artisan", "reverb:start", "--debug"]
    env_file:
      - docker/docker-compose-env/ws-application.env
    links:
      - cache
  cache:
    image: redis:alpine
    container_name: redis-tasker
    command: ['redis-server', '--bind','0.0.0.0','--requirepass', 'testes','--port','6380']
    volumes:
      - redis-data:/data
    ports:
    - "6380:6380"


  webserver:
    build:
      context: .
      dockerfile: ./docker/webserver/dockerfile/webserver.dockerfile
    container_name: webserver-boiler-plate
    restart: on-failure
    volumes:
     - .:/app:rw
     - composer-vendor-data:/app/vendor:rw
     - vite-compiled-data:/app/public/build:rw
     - ./docker/webserver/startup/startup.sh:/app/startup.sh
    ports:
      - 80:80
      - 8003:8003
    depends_on:
      - database
      - cache
      - websocket-server
    env_file:
      - docker/docker-compose-env/application.env
    links:
      - database
      - cache
      - websocket-server

volumes:
   composer-vendor-data:
    driver: "local"
   vite-compiled-data:
    driver: "local"
   postgres15-data:
       driver: local
   redis-data:
       driver: local

