version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres-tasker-app
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    ports:
      - "5433:5432"
    env_file:
      - docker/docker-compose-env/database.env
  php:
    build:
      context: .
      dockerfile: ./docker/php8-fpm/Dockerfile
    image: tasker-api-test-app:v1.0
    container_name: php-tasker
    restart: on-failure
    ports:
      - "9001:9000"
    depends_on:
      - websocket-server
      - database
    command: bash -c "php artisan migrate && php-fpm"
    env_file:
      - docker/docker-compose-env/application.env
    links:
      - database
    volumes:
     - .:/app:rw

  websocket-server:
    build:
      context: .
      dockerfile: ./docker/php8-fpm/Dockerfile
    image: tasker-websocket-app:v1.0
    container_name: tasker-websocket-app
    command: sh -c "php /app/artisan artisan reverb:start --port=8182"
    restart: on-failure
    env_file:
      - docker/docker-compose-env/application.env
    volumes:
      - .:/app:rw
  cache:
    image: redis:alpine
    container_name: redis-tasker
    command: ['redis-server', '--bind','0.0.0.0','--requirepass', 'testes','--port','6380']
    volumes:
      - redis-data:/data
    ports:
    - "6381:6380"
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: tasker-frontend-test-app:v1.0
    container_name: nginx-tasker
    restart: on-failure
    env_file:
      - docker/docker-compose-env/application.env
    depends_on:
      - php
      - websocket-server
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
    ports:
      - 443:443

volumes:
  postgres-data:
    driver: "local"
  redis-data:
    driver: "local"