
services:
  database:
    image: postgres:15
    container_name: postgres-tasker-app
    volumes:
      - postgres15-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    env_file:
      - docker/docker-compose-env/database.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  websocket-server:
    build:
      context: .
      dockerfile: ./docker/php-cli/Dockerfile
    image: tasker-websocket-app:v1.0
    container_name: websocket-tasker
    volumes:
     - .:/app:rw
    ports:
      - "8182:8182"
    command: ["php", "/app/artisan", "reverb:start", "--debug"]
    env_file:
      - docker/docker-compose-env/ws-application.env
    links:
      - cache
  unit-tests:
    build:
      context: .
      dockerfile: ./docker/php-cli/Dockerfile
    image: tasker-unit-tests:v1.0
    container_name: tasker-unit-tests
    volumes:
     - .:/app:rw
     - ./docker/docker-compose-env/testing.env:/app/.env
    command: >
        sh -c "
        php artisan config:clear &&
        php artisan cache:clear &&
        php artisan test
        "
    profiles: ["testing"]

  cache:
    image: redis:alpine
    container_name: redis-tasker
    command: ['redis-server', '--bind','0.0.0.0','--requirepass', 'testes','--port','6380']
    volumes:
      - redis-data:/data
    ports:
    - "6380:6380"


  webserver:
    build:
      context: .
      dockerfile: ./docker/webserver/dockerfile/webserver.dockerfile
    container_name: webserver-boiler-plate
    restart: on-failure
    volumes:
     - .:/app:rw
     - ./docker/webserver/startup/startup.sh:/app/startup.sh
    ports:
      - 80:80
      - 8003:8003
    depends_on:
      - database
      - cache
      - websocket-server
    env_file:
      - docker/docker-compose-env/application.env
    links:
      - database
      - cache
      - websocket-server
  compiler:
    build:
      context: .
      dockerfile: ./docker/compiler/dockerfile/compiler.dockerfile
    container_name: compiler-tasks-maintances
    working_dir: /app
    env_file:
      - docker/docker-compose-env/ws-application.env
    volumes:
     - .:/app:rw
    command:  >
            sh -c "
                composer install --optimize-autoloader &&
                mkdir -p /app/build &&
                npm install --ignore-engines &&
                npm ci --ignore-engines --no-audit --no-fund &&
                npm run build
            "
    profiles: ["compiler"]

volumes:
   postgres15-data:
       driver: local
   redis-data:
       driver: local

